ALTER TABLE fin_detachement DROP FOREIGN KEY `FK_6DC61F15EB355BC8`, ADD FOREIGN KEY `FK_6DC61F15EB355BC8` (`agent_detache_id`) 
        REFERENCES `agent_detache` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE cotisation DROP FOREIGN KEY `FK_AE64D2ED3414710B`, ADD FOREIGN KEY `FK_AE64D2ED3414710B` (`agent_id`) REFERENCES `agent_detache` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

